// A real, recently-fetched-and-verified snapshot of the National Dex Ubers
// Viability Rankings thread, shipped WITH the app as a last-resort fallback
// — NOT the primary source. buildCounterTeam (see ../team-builder.ts)
// always tries the live thread first (see ../vr-thread.ts), then the
// on-disk copy from whatever the last successful live fetch was; this only
// gets used when BOTH of those come up empty, which in practice means a
// deployment whose outbound IP is blocked by Smogon's forum bot-protection
// and has never once completed a live fetch (a hosted platform's shared
// egress IP — Render, Railway, Fly — is the common case; a home connection
// essentially never hits this).
//
// Fetched and parsed from the thread's first post on 2026-08-29 (113
// entries, cross-checked against the live parser's own output — see
// ../vr-thread.ts's parseVrThreadFirstPost/fetchLiveVrMap). Species names
// are already the real @pkmn/dex canonical names (resolved the same way the
// live parser resolves them), so no runtime resolution is needed here.
// This WILL drift from the live thread over time — that's expected and
// fine for a last-resort fallback; if it's ever worth refreshing, just
// re-run fetchLiveVrMap from an unblocked network and paste its JSON output
// back in below.
import type { VrTier } from '../vr-thread.js';

export const GEN9_NATDEX_UBERS_BUNDLED_VR: Record<string, VrTier> = {
  'Groudon-Primal': 'S+',
  'Zacian-Crowned': 'S',
  'Zygarde-Complete': 'S',
  'Ho-Oh': 'S-',
  'Arceus-Dark': 'A+',
  'Arceus-Ground': 'A+',
  Eternatus: 'A+',
  'Kyogre-Primal': 'A+',
  Marshadow: 'A+',
  Yveltal: 'A+',
  Arceus: 'A',
  Lunala: 'A',
  Ditto: 'A-',
  'Necrozma-Dusk-Mane': 'A-',
  'Necrozma-Ultra': 'A-',
  'Salamence-Mega': 'A-',
  'Arceus-Fairy': 'B+',
  'Calyrex-Ice': 'B+',
  'Chi-Yu': 'B+',
  'Deoxys-Attack': 'B+',
  Ferrothorn: 'B+',
  'Giratina-Origin': 'B+',
  Smeargle: 'B+',
  Alomomola: 'B',
  'Deoxys-Speed': 'B',
  'Diancie-Mega': 'B',
  Garganacl: 'B',
  Pheromosa: 'B',
  Rayquaza: 'B',
  'Arceus-Water': 'B-',
  'Chien-Pao': 'B-',
  Fezandipiti: 'B-',
  Glimmora: 'B-',
  'Kyurem-Black': 'B-',
  'Landorus-Therian': 'B-',
  'Arceus-Rock': 'C+',
  Basculegion: 'C+',
  Chansey: 'C+',
  Dondozo: 'C+',
  Giratina: 'C+',
  Kingambit: 'C+',
  Mewtwo: 'C+',
  'Mewtwo-Mega-Y': 'C+',
  Ribombee: 'C+',
  'Arceus-Flying': 'C',
  'Arceus-Ghost': 'C',
  'Arceus-Grass': 'C',
  Clefable: 'C',
  Grimmsnarl: 'C',
  Gothitelle: 'C',
  Hatterene: 'C',
  'Palkia-Origin': 'C',
  Shuckle: 'C',
  'Tapu Lele': 'C',
  Cresselia: 'C-',
  'Darmanitan-Galar': 'C-',
  Dialga: 'C-',
  'Iron Treads': 'C-',
  'Kyurem-White': 'C-',
  Melmetal: 'C-',
  Terapagos: 'C-',
  'Ting-Lu': 'C-',
  'Tyranitar-Mega': 'C-',
  Zekrom: 'C-',
  Annihilape: 'D',
  'Arceus-Bug': 'D',
  'Arceus-Dragon': 'D',
  'Arceus-Electric': 'D',
  'Arceus-Fighting': 'D',
  'Arceus-Fire': 'D',
  'Arceus-Ice': 'D',
  'Arceus-Poison': 'D',
  'Arceus-Psychic': 'D',
  'Arceus-Steel': 'D',
  Baxcalibur: 'D',
  Darkrai: 'D',
  Deoxys: 'D',
  'Dialga-Origin': 'D',
  Dracovish: 'D',
  Dragapult: 'D',
  Espathra: 'D',
  'Flutter Mane': 'D',
  Genesect: 'D',
  Groudon: 'D',
  'Gouging Fire': 'D',
  'Iron Bundle': 'D',
  Kyogre: 'D',
  Landorus: 'D',
  Lugia: 'D',
  Magearna: 'D',
  'Alakazam-Mega': 'D',
  'Blastoise-Mega': 'D',
  'Blaziken-Mega': 'D',
  'Kangaskhan-Mega': 'D',
  'Lucario-Mega': 'D',
  'Mewtwo-Mega-X': 'D',
  'Metagross-Mega': 'D',
  Naganadel: 'D',
  'Ogerpon-Hearthflame': 'D',
  'Necrozma-Dawn-Wings': 'D',
  Palafin: 'D',
  Palkia: 'D',
  Reshiram: 'D',
  'Roaring Moon': 'D',
  'Shaymin-Sky': 'D',
  Solgaleo: 'D',
  Spectrier: 'D',
  Sneasler: 'D',
  'Ursaluna-Bloodmoon': 'D',
  Urshifu: 'D',
  'Walking Wake': 'D',
  Zacian: 'D',
  'Zamazenta-Crowned': 'D',
};
